version: '3'

services:
  basic:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./middleware.js:/app/middleware.js:delegated
      - ./db.js:/app/db.js:delegated
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      VIRTUAL_HOST: json-server.docker

  typescript:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./examples/typescript/db.ts:/app/db.ts
      - ./examples/typescript/middleware.ts:/app/middleware.ts:delegated
    ports:
      - 9998:9998
    environment:
      PORT: 9998
      VIRTUAL_HOST: typescript.json-server.docker

  json-db:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./middleware.js:/app/middleware.js:delegated
      - ./examples/json/db.json:/app/db.json
    ports:
      - 9997:9997
    environment:
      PORT: 9997
      VIRTUAL_HOST: json-db.json-server.docker

  middlewares:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./examples/middlewares/db.json:/app/db.json
      - ./examples/middlewares/middleware.ts:/app/middleware.ts:delegated
    ports:
      - 9996:9996
    environment:
      PORT: 9996
      VIRTUAL_HOST: middlewares.json-server.docker

  deps:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./middleware.js:/app/middleware.js:delegated
      - ./examples/deps/db.js:/app/db.js
    ports:
      - 9995:9995
    environment:
      PORT: 9995
      VIRTUAL_HOST: deps.json-server.docker
      DEPENDENCIES: chance@1 node-emoji@1

  static:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./middleware.js:/app/middleware.js:delegated
      - ./examples/static/db.json:/app/db.json
      - ./examples/static/public:/app/public
    ports:
      - 9993:9993
    environment:
      PORT: 9993
      VIRTUAL_HOST: static.json-server.docker

  dags:
    build: .
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./middleware.js:/app/middleware.js:delegated
      - ./examples/support-files/db.ts:/app/db.ts
      - ./examples/support-files/fixtures:/app/fixtures
    ports:
      - 9994:9994
    environment:
      PORT: 9994
      VIRTUAL_HOST: dags.json-server.docker
