version: '3'

services:
  api:
    build: .
    command: npm run dev
    volumes:
      - ./index.js:/app/index.js
      - ./package.json:/app/package.json:delegated
      - ./routes.json:/app/routes.json:delegated
      - ./middleware.js:/app/middleware.js:delegated
    environment:
      VIRTUAL_HOST: json-server-docker.docker
