name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: codfish/actions/setup-node-and-install@v3

      - name: typecheck ts
        run: pnpm typecheck

      - name: lint js
        run: pnpm lint

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: codfish/json-server

      - name: Build and push
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: codfish/actions/comment@v3
        with:
          message:
            "🚀 PR build published. Run \\`docker run -p 3000:3000 codfish/json-server@${{ steps.build.outputs.digest
            }}\\`"
          tag: pr-build
          upsert: true
